# Generated by Django 3.2.15 on 2025-02-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_alter_orderelements_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderElements',
            new_name='OrderElement',
        ),
    ]
