# Generated by Django 3.2.15 on 2025-03-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_alter_orderelement_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderelement',
            options={'ordering': ['quantity'], 'verbose_name': 'элемент заказа', 'verbose_name_plural': 'элементы заказов'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=250, verbose_name='описание'),
        ),
    ]
