# Generated by Django 3.2.15 on 2025-03-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_order_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_cost',
            field=models.FloatField(default=0.0, verbose_name='стоимость заказа'),
        ),
    ]
