# Generated by Django 3.2.15 on 2025-03-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_order_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderelement',
            options={'ordering': ['cost'], 'verbose_name': 'элемент заказа', 'verbose_name_plural': 'элементы заказов'},
        ),
        migrations.AddField(
            model_name='orderelement',
            name='cost',
            field=models.FloatField(default=0.0, verbose_name='стоимость заказа'),
        ),
    ]
