# Generated by Django 3.2.15 on 2025-03-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20250316_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderelement',
            options={'ordering': ['quantity'], 'verbose_name': 'элемент заказа', 'verbose_name_plural': 'элементы заказов'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_cost',
        ),
        migrations.RemoveField(
            model_name='orderelement',
            name='cost',
        ),
    ]
