# Generated by Django 3.2.15 on 2025-03-19 08:10

from django.db import migrations


def move_body(apps, schema_editor):
    OrderElement = apps.get_model('foodcartapp', 'OrderElement')
    for order_el in OrderElement.objects.filter(price=0.0):
        order_el.price = order_el.product.price * order_el.quantity
        order_el.save()

def reverse_move_body(apps, schema_editor):
    OrderElement = apps.get_model('foodcartapp', 'OrderElement')
    OrderElement.objects.all().update(price=0.0)


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_alter_orderelement_price'),
    ]

    operations = [
        migrations.RunPython(move_body, reverse_move_body)
    ]
