# Generated by Django 3.2.15 on 2025-03-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20250319_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('under', 'на рассмотрении'), ('unprocessed', 'необработанный'), ('accepted', 'принят'), ('completed', 'выполнен')], db_index=True, default='unprocessed', max_length=30, verbose_name='статус'),
        ),
    ]
