# Generated by Django 3.2.15 on 2025-03-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order collected', 'заказ собран'), ('unprocessed', 'необработанный'), ('handed over to the courier', 'передан курьеру'), ('completed', 'выполнен')], db_index=True, default='unprocessed', max_length=30, verbose_name='статус'),
        ),
    ]
