# Generated by Django 3.2.15 on 2025-03-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_alter_order_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('electronically', 'Электронно'), ('in_cash', 'Наличностью')], db_index=True, default='in_cash', max_length=30, verbose_name='способ оплаты'),
        ),
    ]
