# Generated by Django 3.2.15 on 2025-04-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='адрес места')),
                ('lng', models.DecimalField(decimal_places=2, max_digits=8, unique=True, verbose_name='долгота')),
                ('lat', models.DecimalField(decimal_places=2, max_digits=8, unique=True, verbose_name='широта')),
                ('date', models.DateTimeField(verbose_name='дата')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'места',
            },
        ),
    ]
