# Generated by Django 3.2.15 on 2025-04-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20250407_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='долгота'),
        ),
    ]
