# Generated by Django 3.2.15 on 2025-04-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20250409_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='date',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='дата'),
        ),
    ]
